import React, { Fragment, useState, useEffect } from "react";
import styles from "./Section17.module.css";
import SectionHead from "./SectionHead";
import SectionButtons from "./SectionButtons";
import SectionFaq from "./SectionFaq";

const faqData = [
  {
    id: 1,
    section_id: 1,
    section_name: "Our Services",
    question: "What services does AOB India offer?",
    answer:
      "AOB India provides a range of sales outsourcing solutions, including Sales Consulting, Qualified Lead Generation, Qualified Meeting Generation, and End-to-End Sales Outsourcing. We tailor our services to meet the specific needs of each client, ensuring optimal results.",
  },
  {
    id: 2,
    section_id: 1,
    section_name: "Our Services",
    question: "What is the difference between a lead and a qualified lead?",
    answer:
      "A lead is a potential customer who has shown some interest in a product or service, while a qualified lead is someone who meets specific criteria that indicate a high likelihood of converting into a customer. Qualified leads are pre-screened to ensure they match your business's target demographic and show genuine interest in your offerings.",
  },
  {
    id: 3,
    section_id: 1,
    section_name: "Our Services",
    question: "How does AOB India’s Qualified Lead Generation service work?",
    answer:
      "Our Qualified Lead Generation service involves using advanced AI tools to identify potential leads, followed by a thorough qualification process. This includes tele calling to verify interest and suitability, ensuring that only high-quality leads are passed on to our clients.",
  },
  {
    id: 4,
    section_id: 1,
    section_name: "Our Services",
    question: "Can you explain the Qualified Meeting Generation service?",
    answer:
      "Our Qualified Meeting Generation service focuses on setting up meetings between our clients and highly qualified prospects. We handle the entire process, from identifying potential leads to scheduling meetings, ensuring that our clients meet with decision-makers who have a genuine interest in their products or services.",
  },
  {
    id: 5,
    section_id: 1,
    section_name: "Our Services",
    question: "What industries do you serve? ",
    answer:
      "We serve a wide range of industries, including Real Estate, Healthcare, Education, Financial Services, Manufacturing, Retail, Technology, and many others. Our solutions are customized to fit the unique needs of each industry.",
  },
  {
    id: 6,
    section_id: 2,
    section_name: "Lead Process",
    question: "How does AOB QLead qualify leads?",
    answer:
      "After generating leads through predictive scoring, our tele callers engage with the leads using dynamic scripts generated by AI tools. The conversations are monitored for quality, and the leads are qualified based on predefined criteria. The entire process is supported by AI tools, ensuring accuracy and efficiency.",
  },
  {
    id: 7,
    section_id: 2,
    section_name: "Lead Process",
    question: "What information is provided with a qualified lead? ",
    answer:
      "Each qualified lead comes with comprehensive details, including the prospect's name, contact information, website, email address, qualification call transcript, voice recording, and harmonic analysis report. This ensures that our clients have all the necessary information to convert the lead into a customer.",
  },
  {
    id: 8,
    section_id: 2,
    section_name: "Lead Process",
    question: "How do you ensure the quality of leads?",
    answer:
      "We use advanced AI tools and a rigorous qualification process to ensure the quality of leads. Our tele callers follow dynamic scripts tailored to each lead, and all interactions are monitored for compliance and quality. Only leads that meet all predefined criteria are passed on to our clients.",
  },
  {
    id: 9,
    section_id: 2,
    section_name: "Lead Process",
    question:
      "What is harmonic analysis, and how does it help in lead qualification? ",
    answer:
      "Harmonic analysis is an AI-driven technique used to analyze the tone, sentiment, and quality of conversations between our tele callers and leads. It helps identify the lead's intent and readiness to purchase, ensuring that only high-quality leads are passed on to our clients.",
  },
  {
    id: 10,
    section_id: 3,
    section_name: "AI Tools",
    question: "What AI tools do you use for lead generation and qualification?",
    answer:
      "We use a range of advanced AI tools, including predictive scoring algorithms, dynamic script generation, harmonic analysis, and real-time monitoring systems. These tools help us identify, engage, and qualify leads with high accuracy and efficiency.",
  },
  {
    id: 11,
    section_id: 3,
    section_name: "AI Tools",
    question: "How does predictive lead scoring work?",
    answer:
      "Predictive lead scoring uses AI algorithms to analyze data from various sources and predict the likelihood of a lead converting into a customer. This helps prioritize leads based on their potential value, ensuring that our clients focus on the most promising prospects.",
  },
  {
    id: 12,
    section_id: 3,
    section_name: "AI Tools",
    question: "Can you explain the dynamic script generation process?",
    answer:
      "Dynamic script generation involves using AI tools to create customized scripts for tele callers based on the lead's profile and source of generation. This ensures that each interaction is personalized and relevant, increasing the chances of successful lead qualification.",
  },
  {
    id: 13,
    section_id: 3,
    section_name: "AI Tools",
    question: "What is the role of AI in monitoring and ensuring compliance?",
    answer:
      "AI tools monitor all interactions between telecalls and leads in real-time, ensuring compliance with quality standards and predefined criteria. This helps maintain the integrity of the lead qualification process and ensures that only high-quality leads are passed on to our clients.",
  },
  {
    id: 14,
    section_id: 4,
    section_name: "Client Support",
    question: "What kind of support do you offer to your clients? ",
    answer:
      "We offer comprehensive support to our clients, including dedicated account managers, regular performance reviews, and ongoing optimization of campaigns. Our goal is to ensure that our clients achieve the best possible results from our services.",
  },
  {
    id: 15,
    section_id: 4,
    section_name: "Client Support",
    question:
      "How do you measure the success of your lead generation campaigns?",
    answer:
      "We measure the success of our campaigns through various metrics, including the number of qualified leads generated, conversion rates, client feedback, and overall ROI. Regular performance reviews help us identify areas for improvement and ensure that our clients achieve their goals.",
  },
  {
    id: 16,
    section_id: 4,
    section_name: "Client Support",
    question:
      "Can you provide references or case studies from previous clients? ",
    answer:
      "Yes, we can provide references and case studies from a wide range of industries. These demonstrate our expertise and the success we have achieved for our clients through our lead generation and qualification services.",
  },
  {
    id: 17,
    section_id: 4,
    section_name: "Client Support",
    question: "How do I get started with AOB QLead?",
    answer:
      "Getting started with AOB QLead is easy. Simply contact us through our website or reach out to one of our sales representatives. We will schedule a consultation to understand your needs and create a customized lead generation strategy for your business.",
  },

  {
    id: 18,
    section_id: 5,
    section_name: "Predictive Analysis",
    question: "What is predictive lead scoring, and how does AOB QLead use it?",
    answer:
      "Predictive lead scoring uses AI and machine learning to evaluate leads based on past behaviour, demographic information, and engagement levels. AOB QLead employs predictive lead scoring to prioritize leads that are most likely to convert, ensuring your sales team focuses on the most promising prospects.",
  },
  {
    id: 19,
    section_id: 5,
    section_name: "Predictive Analysis",
    question: "How does predictive lead analysis work at AOB QLead?",
    answer:
      "Predictive lead analysis uses AI algorithms to evaluate data from various sources, predicting the likelihood of a lead converting into a customer. This helps prioritize leads based on their potential, ensuring a more focused and effective sales approach.",
  },
  {
    id: 20,
    section_id: 5,
    section_name: "Predictive Analysis",
    question: "What data is used in predictive lead analysis?",
    answer:
      "We use a variety of data, including historical sales data, demographic information, behavioural patterns, and interaction history. This comprehensive approach ensures accurate and reliable lead scoring.",
  },

  {
    id: 21,
    section_id: 6,
    section_name: "Harmonic Analysis",
    question: "What is harmonic analysis, and why is it beneficial?",
    answer:
      "Harmonic analysis evaluates the tone, sentiment, and delivery of lead interactions to gauge their interest and readiness to purchase. This deeper insight helps prioritize leads and improve conversion rates by focusing on those most likely to convert.",
  },
  {
    id: 22,
    section_id: 6,
    section_name: "Harmonic Analysis",
    question: "What is harmonic analysis in lead qualification?",
    answer:
      "Harmonic analysis is an AI-driven technique that evaluates the tone, sentiment, and quality of conversations between tele callers and leads. It helps assess the lead’s intent and readiness to purchase, ensuring that only the most qualified leads are passed on to our clients.",
  },
  {
    id: 23,
    section_id: 6,
    section_name: "Harmonic Analysis",
    question: "How does harmonic analysis benefit my business?",
    answer:
      "Harmonic analysis provides deeper insights into lead quality, allowing for more effective follow-ups and higher conversion rates. It ensures that you receive leads that are genuinely interested and ready to engage with your products or services.",
  },
  {
    id: 24,
    section_id: 7,
    section_name: "Conversion Rate",
    question: "What conversion rates can I expect for my industry?",
    answer:
      "Conversion rates vary by industry, but our AI-driven lead qualification process ensures higher conversion rates compared to traditional methods. For specific conversion rates in your industry, we can provide data based on our extensive experience and past campaigns.",
  },
  {
    id: 25,
    section_id: 7,
    section_name: "Conversion Rate",
    question: "How does AOB QLead improve conversion rates?",
    answer:
      "By using advanced AI tools for lead scoring and qualification, personalized engagement, and rigorous quality checks, we ensure that the leads you receive are highly relevant and ready to convert, resulting in higher conversion rates.",
  },
  {
    id: 26,
    section_id: 8,
    section_name: "Digital Comparison.",
    question: "Why is AOB QLead better than leads from Google or Facebook?",
    answer:
      "Unlike platforms like Google and Facebook, which charge for all leads regardless of quality, AOB QLead provides only qualified leads. This means you're paying for leads that have been vetted and match your specific criteria, reducing the time and resources spent on unqualified leads. Additionally, our leads come with detailed demographic information, conversation transcripts, and harmonic analysis, offering deeper insights.",
  },
  {
    id: 27,
    section_id: 8,
    section_name: "Digital Comparison.",
    question: "How is QLead better than digital marketing leads?",
    answer:
      "Unlike traditional digital marketing leads, QLead focuses on providing highly qualified leads that have been vetted through AI tools and personalized engagement. This results in higher conversion rates and better ROI for your business.",
  },
  {
    id: 28,
    section_id: 8,
    section_name: "Digital Comparison.",
    question:
      "What are the advantages of using QLead over digital marketing leads?",
    answer:
      "QLead offers several advantages, including predictive lead scoring, personalized engagement, harmonic analysis, and comprehensive lead qualification. This ensures that you receive leads that are more likely to convert, saving you time and resources.",
  },
  {
    id: 29,
    section_id: 9,
    section_name: "Lead Cost",
    question: "Why are qualified leads more expensive?",
    answer:
      " Qualified leads are more expensive because they have undergone a rigorous qualification process, including predictive scoring, tele calling, and harmonic analysis. This ensures that the leads you receive are highly relevant and ready to convert, providing better ROI. This thorough process involves significant time and resource investment, which is reflected in the cost.",
  },
  {
    id: 30,
    section_id: 9,
    section_name: "Lead Cost",
    question: "How does the cost of qualified leads justify the investment?",
    answer:
      "Although qualified leads are more expensive, they offer a higher conversion rate and better ROI. By focusing on leads that are ready to engage, you save time and resources, ultimately driving more sales and revenue for your business.",
  },
  {
    id: 31,
    section_id: 9,
    section_name: "Lead Cost",
    question:
      "Since qualified lead costs are high, will I receive fewer leads?",
    answer:
      "While the cost per qualified lead is higher, the value lies in their quality and conversion potential. You may receive fewer leads compared to a bulk lead generation approach, but these leads are more likely to result in successful conversions, offering a better return on investment.",
  },
  {
    id: 32,
    section_id: 10,
    section_name: "Pricing & Packages",
    question: "How is the cost per lead determined? ",
    answer:
      "The cost per lead is determined based on various factors, including the industry, target audience, lead qualification criteria, and sales goals. We provide customized pricing packages to ensure the best value for our clients.",
  },
  {
    id: 33,
    section_id: 10,
    section_name: "Pricing & Packages",
    question: "What are the different pricing packages available for QLead?",
    answer:
      "We offer several pricing packages for QLead, including:Accelerator Package:  Suitable for medium-sized businesses, offering a moderate number of leads with additional features. Expansion Package: Designed for larger businesses, providing a high volume of qualified leads and premium support. Enterprise Package:  Customized solutions for large enterprises with extensive lead generation needs.",
  },
  {
    id: 34,
    section_id: 10,
    section_name: "Pricing & Packages",
    question: "Is there a setup fee for your services?",
    answer:
      "Yes, there is a one-time platform setup fee of INR 15,000. This includes campaign setup, creatives cost, lead persona building, lead funnel setup, lead qualification parameter setup, AI tools deployment, and other related costs.",
  },
  {
    id: 35,
    section_id: 10,
    section_name: "Pricing & Packages",
    question: "Are there any additional costs involved? ",
    answer:
      "Beyond the setup fee and the cost per lead or meeting, there may be additional costs for specific services or customizations. We provide a detailed breakdown of all costs upfront, ensuring complete transparency.",
  },
  {
    id: 36,
    section_id: 10,
    section_name: "Pricing & Packages",
    question:
      "How quickly can AOB QLead deliver qualified leads after payment?",
    answer:
      "Once the platform fee is paid and the lead qualification criteria are set, AOB QLead can deliver qualified leads within 6 to 12 working days, depending on the criteria and lead type. In many cases, leads are delivered even faster.",
  },
  {
    id: 37,
    section_id: 10,
    section_name: "Pricing & Packages",
    question: "Does AOB QLead offer free sample leads?",
    answer:
      "As a policy, AOB QLead does not provide free sample leads. We focus on delivering qualified leads that meet your criteria, ensuring value for your investment. Unlike other platforms, we do not charge for unqualified or junk leads.",
  },
];

const Section17 = () => {
  const [activeTab, setActiveTab] = useState(1);
  const [activeFaqData, setActiveFaqData] = useState([]);

  const filtersFaqs = () => {
    const res = faqData.filter((item) => item.section_id === activeTab);
    setActiveFaqData(res);
  };

  useEffect(() => {
    filtersFaqs();
  }, [activeTab]);

  const buttonClickHandler = (id) => {
    setActiveTab(id);
  };

  return (
    <Fragment>
      <SectionHead />
      <SectionButtons
        categories={faqData}
        onClick={(id) => buttonClickHandler(id)}
        active={activeTab}
      />
      <SectionFaq questions={activeFaqData} activeTab={activeTab} />
    </Fragment>
  );
};

export default Section17;
